echo %*
rem c:\utils\ffmpeg.exe -i %*
rem set /p DUMMY=Hit ENTER to continue...
rem c:\utils\ffmpeg.exe -i %* -map 0:p:1 -c copy C:\Kodi16.1\portable_data\userdata\out.ts
rem c:\utils\ffmpeg.exe -y -i %*  -c copy  C:\Kodi16.1\portable_data\userdata\out.ts
set /p DUMMY=Hit ENTER to continue...